### ISSUE TITLE
Can't run the bot

### ISSUE THREAD

**Issue by Jgreer52** [MinusGix/DiscordModelHogwartsBot#10]
I have followed your guide to the letter. But when I try to run the index.js i get this error 

```
Error: Cannot find module 'C:\Users\JGree\Downloads\DiscordModelHogwartsBot-master\index.js'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:687:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}
```
So the bot is in my server, but it is not "live" and will not respond to commands.

**Comment by MinusGix** [comment]
That's what happens when you run `node` with an invalid filename. I'd check that you're doing it in the correct directory.  
Also, the zip file you download has to be unzipped (assuming you haven't done that).

**Comment by Jgreer52** [comment]
Yes. I have it unzipped. I have tried it at various places, but I assure you that the file path listed above is where the index.js actually is. I will try some more and maybe post some screenshots if that would help you help me. Lol. Thanks for the reply.

**Comment by Jgreer52** [comment]
![cmd error](https://user-images.githubusercontent.com/30992940/68606876-03396800-0475-11ea-957b-e880d325901a.JPG)

**Comment by MinusGix** [comment]
You have to run `npm install` in that folder.

**Comment by Jgreer52** [comment]
Awesome. You are correct. That worked. Thanks!
