### ISSUE TITLE
Trouble with permissions for Commands

### ISSUE THREAD

**Issue by Jgreer52** [MinusGix/DiscordModelHogwartsBot#11]
I posted my files in #1 ,but I didn't know if I needed to start a new problem since the other one was closed. Sorry if this is redundant.  

I'm having the same issue as #1 here are my screenshots. One of my config, and one of my cmd prompt showing the actions I took. 
![config file](https://user-images.githubusercontent.com/30992940/68612147-78129f00-0481-11ea-9a12-8402b9767da3.JPG)
![image](https://user-images.githubusercontent.com/30992940/68612186-8b256f00-0481-11ea-8316-60dcd0cf06ec.png)

**Comment by MinusGix** [comment]
If I'm remembering correctly, then the role names in the file have to be lowercase. So `"order of the phoenix"` in the file. Though, they can still be mixed-case in the actual role.
This is due to a slightly bad way I coded those checks.

**Comment by Jgreer52** [comment]
I'm away from my computer till tomorrow. Thanks for the reply. I'll try this tomorrow.

**Comment by Jgreer52** [comment]
This worked! Thanks

**Comment by MinusGix** [comment]
Glad it worked.
