### ISSUE TITLE
Commands not working - permission issue?

### ISSUE THREAD

**Issue by dubuhaseul** [MinusGix/DiscordModelHogwartsBot#2]
A simple google search reveals that this issue has affected a few people so I'm surprised that an issue hasn't been opened before.

As far as I can tell, all of the commands work, except the ones that require a mod permission - eg: the add command. 

Or am I just missing something really obvious?
(which is the most likely scenario)

**Comment by MinusGix** [comment]
My reply to this should work, unless I'm misunderstanding your issue: https://github.com/MinusGix/DiscordModelHogwartsBot/issues/1
If you need any further help, or I misunderstand the problem, just reply and I'll try helping.

**Comment by MinusGix** [comment]
I'll assume you got this working, if you didn't just reply.
