### ISSUE TITLE
Hogwarts bot

### ISSUE THREAD

**Issue by RazzmicBerrry** [MinusGix/DiscordModelHogwartsBot#3]
I am having the exact same problem as Issue #1. I tried to do the fix you presented, but it isn't working for me. I have many roles that I've made for my server and I have tried a few of them in turn. I just keep getting the same message.

**Comment by MinusGix** [comment]
Did you restart the bot after any changes?
Did you rename example_config.json to config.json? 
Is there any errors in the terminal, if so post them here.
Can you post your config.json? (Making sure to remove your bot's token)

Try those, the last one will let me see if there's an issue with your config file.

Sorry about taking so long, for some reason Github gives me notifications several days after the fact.

**Comment by MinusGix** [comment]
I'll assume you got this fixed. If you're still having issues related to this, just reply.
