### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by DiscordGitHub1** [MinusGix/DiscordModelHogwartsBot#5]
So, everything is okay, I invited the bot to my discord server but of course it's offline I tried to make it online with the npm command and it says:
Error: Cannot find module 'discord.js'

It also says: Error: Incorrect login details were provided.

**Comment by MinusGix** [comment]
>Cannot find module 'discord.js'  

You probably have to run `npm install`, as that will install discord.js (a library I use to make it easier to interact with discord).  
Try running it once that succeeds (or tell me if there's any errors with the install)
If it says Incorrect Login Details still, then you need to put the bot token in the config file.

**Comment by DiscordGitHub1** [comment]
Thanks! <3
